"""Add make_name to Car model

Revision ID: 271cfc486060
Revises: d9694c2afc1b
Create Date: 2023-12-17 14:53:42.489579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "271cfc486060"
down_revision: Union[str, None] = "d9694c2afc1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cars", sa.Column("make_name", sa.String(), nullable=True))


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cars", "make_name")
    # ### end Alembic commands ###
