"""Add model_webpage column to cars table

Revision ID: 2de6c73b3ad5
Revises: b5ef29d9437d
Create Date: 2024-03-16 08:41:25.925207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2de6c73b3ad5'
down_revision: Union[str, None] = 'b5ef29d9437d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('model_webpage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cars", "model_webpage")
    # ### end Alembic commands ###
