"""change field names to car_description and model_description

Revision ID: b5ef29d9437d
Revises: f6072caceec8
Create Date: 2023-12-24 06:46:44.770939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b5ef29d9437d"
down_revision: Union[str, None] = "f6072caceec8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("cars", "desc", new_column_name="car_description")
    op.alter_column("cars", "model_desc", new_column_name="model_description")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("cars", "car_description", new_column_name="desc")
    op.alter_column("cars", "model_description", new_column_name="model_desc")
    # ### end Alembic commands ###
