"""Add vehicle availability and availability desc

Revision ID: d9694c2afc1b
Revises: dad2c4b18f57
Create Date: 2023-12-17 07:20:31.305544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d9694c2afc1b"
down_revision: Union[str, None] = "dad2c4b18f57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cars", sa.Column("availability_desc", sa.String(), nullable=True))
    op.add_column(
        "cars",
        sa.Column("production_availability", sa.Boolean(), nullable=True, default=True),
    )

    # Set default value for existing records
    op.execute(
        "UPDATE cars SET production_availability = true WHERE production_availability IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cars", "production_availability")
    op.drop_column("cars", "availability_desc")
    # ### end Alembic commands ###
