"""Add model_desc to car model

Revision ID: f6072caceec8
Revises: 271cfc486060
Create Date: 2023-12-23 12:20:26.815599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f6072caceec8"
down_revision: Union[str, None] = "271cfc486060"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cars", sa.Column("model_desc", sa.Text, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cars", "model_desc")
    # ### end Alembic commands ###
