"""swap from sqlite to postgres

Revision ID: fef08c46f1fd
Revises: 
Create Date: 2023-11-30 17:06:08.309399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fef08c46f1fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_people_id', table_name='people')
    op.drop_table('people')
    op.drop_index('ix_makes_id', table_name='makes')
    op.drop_index('ix_makes_name', table_name='makes')
    op.drop_table('makes')
    op.drop_table('make_founders_association')
    op.drop_index('ix_cars_id', table_name='cars')
    op.drop_index('ix_cars_model', table_name='cars')
    op.drop_table('cars')
    op.drop_table('make_person_association')
    op.drop_table('make_ceo_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('make_ceo_association',
    sa.Column('make_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['makes.id'], name='make_ceo_association_make_id_fkey'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name='make_ceo_association_person_id_fkey')
    )
    op.create_table('make_person_association',
    sa.Column('make_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['makes.id'], name='make_person_association_make_id_fkey'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name='make_person_association_person_id_fkey')
    )
    op.create_table('cars',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('make_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('submodel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('generation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('acceleration_0_60', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('current_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('epa_range', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('number_of_full_adult_seats', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('available_countries', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('battery_capacity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('battery_max_charging_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bidirectional_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('chargers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('carmodel_first_released', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('carmodel_ended', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('trim_ended', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('trim_first_released', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('color_options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('customer_and_critic_rating', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('drive_assist_features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('drive_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('frunk_capacity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('has_spare_tire', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('power', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('top_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('torque', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('speed_acc', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('price_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('reviews', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('range_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('euroncap_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nhtsa_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sentry_security', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sentry_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('camping_features', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('dog_mode', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('infotainment_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('interior_ambient_lighting_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('keyless', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('number_of_passenger_doors', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remote_heating_cooling', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('seating_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('towing_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('regen_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('vehicle_class', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vehicle_sound_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['makes.id'], name='cars_make_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cars_pkey')
    )
    op.create_index('ix_cars_model', 'cars', ['model'], unique=False)
    op.create_index('ix_cars_id', 'cars', ['id'], unique=False)
    op.create_table('make_founders_association',
    sa.Column('make_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['makes.id'], name='make_founders_association_make_id_fkey'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name='make_founders_association_person_id_fkey')
    )
    op.create_table('makes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ceo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ceo_pay', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('headquarters', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('founding_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('market_cap', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('num_ev_models', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_ev_model_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unionized', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('lrg_logo_img_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ceo_id'], ['people.id'], name='makes_ceo_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='makes_pkey')
    )
    op.create_index('ix_makes_name', 'makes', ['name'], unique=False)
    op.create_index('ix_makes_id', 'makes', ['id'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('university_degree', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('strengths', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('weaknesses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='people_pkey')
    )
    op.create_index('ix_people_id', 'people', ['id'], unique=False)
    # ### end Alembic commands ###
